#' Request BLS index
#'
#' This function returns a number of specified series from the BLS as a
#' `data.table::data.table()` with `year`, `month`, and `index`.
#'
#' @author Issaac Hansen
#' @param query an API request for the BLS website generated by `bls_query()`
#' @returns A `data.table::data.table()` containing 3 columns: `year`, `month`, and `index`
#' @export
#'
bls_request <- function(
    query
){
  # Send web request
  request <- httr::GET(url = query)

  # Raise error if faulty response code
  if (httr::status_code(request) != 200) {
    base::stop("Error! API request failed!")
  }

  # Unpack to data element
  data <- httr::content(request)$Results$series[[1]]$data

  # Return data element
  return(data)
}
